server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:analysisdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


file.service.url: ${FILE_SERVICE_URL:http://localhost:8081}